import { Request, Response, NextFunction } from 'express';
import { verifyToken } from './jwt.js';
import { getDeviceByAgentToken, type DeviceRow } from '../db/devices.js';

declare global {
  namespace Express {
    interface Request {
      user?: { userId: number; account: string };
      // 2026-06-06: agent request context. Set by agentAuthMiddleware.
      // Distinct from `user` because agents authenticate as devices, not as
      // human users. Allows the same router to host both if needed.
      agent?: { deviceId: number; userId: number; device: DeviceRow };
    }
  }
}

export function authMiddleware(req: Request, res: Response, next: NextFunction) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.status(401).json({ code: 401, message: 'Authentication required' });
    return;
  }

  const token = authHeader.slice(7);
  const payload = verifyToken(token);
  if (!payload) {
    res.status(401).json({ code: 401, message: 'Invalid or expired token' });
    return;
  }

  req.user = { userId: payload.userId, account: payload.account };
  next();
}

/**
 * 2026-06-06: agent bearer-token auth. Resolves the token to a device row
 * and sets req.agent. Used by routes mounted under /api/agents/* — the
 * agent presents its `AGENT_TOKEN` env var as `Authorization: Bearer ...`.
 *
 * Distinct from `authMiddleware` (human JWT). Do NOT chain both — pick one.
 * The agent token is a per-device UUID, generated by the server on device
 * create. It grants no access to user-facing routes; it only allows the
 * agent to register/heartbeat/shutdown for its own device and to receive
 * launch requests from the executor for that device.
 */
export function agentAuthMiddleware(req: Request, res: Response, next: NextFunction) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    res.status(401).json({ code: 401, message: 'Agent token required' });
    return;
  }

  const token = authHeader.slice(7).trim();
  if (!token) {
    res.status(401).json({ code: 401, message: 'Agent token required' });
    return;
  }

  const device = getDeviceByAgentToken(token);
  if (!device) {
    res.status(401).json({ code: 401, message: 'Invalid agent token' });
    return;
  }

  req.agent = { deviceId: device.id, userId: device.user_id, device };
  next();
}
